runtime: python311
service: default
entrypoint: python bot.py

manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: server.settings

instance_class: B4