steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update && apt-get install -y python3.11-venv
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
    gcloud app create --region=asia-south1
    gcloud app deploy --quiet

options:
  logging: CLOUD_LOGGING_ONLY